// Generated by Maglev codegen
import * as CoreTypes from '../../src/runtime/types'

const sectionDefinitionMapping: CoreTypes.SectionDefinitionMapping = {
  cta_01: {
    settings: {
      title: 'text',
      body: 'text',
      background_image: 'image'
    },
    blocks: {
    }
  },
  feature_01: {
    settings: {
      title: 'text',
      body: 'text'
    },
    blocks: {
      feature_item: {
        settings: {
          name: 'text',
          icon: 'icon',
          description: 'text'
        }
      }
    }
  }
}

export default sectionDefinitionMapping
