// Generated by Maglev codegen
import * as CoreTypes from '../../src/runtime/types'

export type Cta01Section = CoreTypes.Section & {
  id: string
  settings: {
    title: CoreTypes.TextSetting
    body: CoreTypes.TextSetting
    background_image: CoreTypes.ImageSetting
  }
}

export type Feature01SectionFeatureItemBlock = {
  id: string
  settings: {
    name: CoreTypes.TextSetting
    icon: CoreTypes.IconSetting
    description: CoreTypes.TextSetting
  }
}

export type Feature01Section = CoreTypes.Section & {
  id: string
  settings: {
    title: CoreTypes.TextSetting
    body: CoreTypes.TextSetting
  }
  blocks: (Feature01SectionFeatureItemBlock)[]
}
