// Generated by Maglev codegen
import * as CoreTypes from '../../src/runtime/types'

export type Cta01Section = CoreTypes.Section & {
  id: string
  settings: {
    title: CoreTypes.TextSetting
    body: CoreTypes.TextSetting
    background_image: CoreTypes.ImageSetting
  }
}

export type Feature01SectionFeatureItemBlock = {
  id: string
  settings: {
    name: CoreTypes.TextSetting
    icon: CoreTypes.IconSetting
    description: CoreTypes.TextSetting
  }
}

export type Feature01Section = CoreTypes.Section & {
  id: string
  settings: {
    title: CoreTypes.TextSetting
    body: CoreTypes.TextSetting
  }
  blocks: (Feature01SectionFeatureItemBlock)[]
}

const sectionDefinitionMapping: CoreTypes.SectionDefinitionMapping = {
  cta_01: {
    settings: {
      title: 'text',
      body: 'text',
      background_image: 'image'
    },
    blocks: {
    }
  },
  feature_01: {
    settings: {
      title: 'text',
      body: 'text'
    },
    blocks: {
      feature_item: {
        settings: {
          name: 'text',
          icon: 'icon',
          description: 'text'
        }
      }
    }
  }
}

export { sectionDefinitionMapping }
